package com.sailens.domain.model.scene

import com.sailens.domain.model.perception.MlRuntimeInfo

data class SceneDebugInfo(
    val semanticProvider: String,
    val obstacleProvider: String,
    val perceptionProfile: String,
    val semanticRuntimeInfo: MlRuntimeInfo,
    val obstacleRuntimeInfo: MlRuntimeInfo,
    val passableRatio: Float,
    val navigationPassableRatio: Float,
    val navigationPassableDelta: Float,
    val obstacleRatio: Float,
    val roadRatio: Float,
    val roadRatioDelta: Float,
    val bottomCoverage: Float,
    val bottomMaxRunWidthRatio: Float,
    val blockageConfidence: Float,
    val blockageConfidenceDelta: Float,
    val blockageReason: String,
    val occludedPassableRatio: Float,
    val verticalReachRatio: Float,
    val verticalReachDelta: Float,
    val floodReachRatio: Float,
    val floodReachDelta: Float,
    val widthRetentionP25: Float,
    val widthRetentionP25Delta: Float,
    val validLayers: Int,
    val totalLayers: Int,
    val dominantClasses: List<String>,
    val processFrameMs: Long,
    val inferenceMs: Long,
    val analyzeSceneMs: Long,
    val decideEventsMs: Long,
    val totalPipelineMs: Long,
    val droppedFramesSinceLast: Int,
    val recentAvgTotalPipelineMs: Double,
    val recentP95TotalPipelineMs: Long,
    val recentDroppedFrameRate: Double,
    val isRuntimeOverBudget: Boolean,
    val trackedObstacleCount: Int,
    val rawObstacleDetectionCount: Int,
    val obstacleCountDelta: Int,
    val rawObstacleDetectionCountDelta: Int,
    val rawObstacleClassNames: List<String> = emptyList(),
    val trackedObstacleCategories: List<String> = emptyList(),
    val roadVehicleSource: String = "none",
    val roadVehicleConfidence: Float = 0f,
    val roadVehicleReason: String = "none",
    val roadVehicleBottomY: Float = 0f,
    val roadVehicleCenterBandOverlap: Float = 0f,
    val roadVehicleAreaRatio: Float = 0f,
)
